services:
  fa-notify:
    build: .
    restart: unless-stopped
    environment:
      FA_NOTIFY_CONFIG: /app/settings.json
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    volumes:
      - ./cookies.txt:/app/cookies.txt:ro
      - ./settings.json:/app/settings.json:ro
      - ./fa-notifier/data:/data
      - ./fa-notifier/logs:/logs

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.5.2
    profiles: [solver]
    restart: unless-stopped
    environment:
      LOG_LEVEL: error
      LOG_HTML: "false"
      DISABLE_MEDIA: "true"
